// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khlvxxjjezllxrmfchob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobHZ4eGpqZXpsbHhybWZjaG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDQ0NzUsImV4cCI6MjA3MjMyMDQ3NX0.7j8pC0TRGoMq7JkgR0gS8wc6yp6i-Bz5mELwyccZwEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});